name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install yarn
        run: npm i -g yarn

      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build
